name: flutter_application_1
description: A new Flutter project.

environment:
  sdk: ">=2.17.0 <3.0.0"

#dependencies:
#  flutter:
#    sdk: flutter
#  http: ^1.2.2
#  carousel_slider: ^5.0.0
#  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter 

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  carousel_slider: ^5.0.0
  google_fonts: ^6.2.1
  dartz: ^0.10.1
  cached_network_image: ^3.2.3

flutter:
  assets:
    - assets/logo.png
    - assets/backgroundApp.png
    - assets/backgroundHome.png
